// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAaHNXzGmhJjWcBcv8zoasKoJxmRjIDnps',
    appId: '1:939281998082:web:d665e01023c1365706621b',
    messagingSenderId: '939281998082',
    projectId: 'moviles-e0d1e',
    authDomain: 'moviles-e0d1e.firebaseapp.com',
    storageBucket: 'moviles-e0d1e.appspot.com',
    measurementId: 'G-LNX2QVV1EE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfwtv9AtiU9_-Ogs95zcYjcYIY9WcTgEg',
    appId: '1:939281998082:android:5c06d5467c55a07606621b',
    messagingSenderId: '939281998082',
    projectId: 'moviles-e0d1e',
    storageBucket: 'moviles-e0d1e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7vGyEwvprHQ6C8hh8zatg--ymGEmdgJc',
    appId: '1:939281998082:ios:dfb0b9489c9a082906621b',
    messagingSenderId: '939281998082',
    projectId: 'moviles-e0d1e',
    storageBucket: 'moviles-e0d1e.appspot.com',
    iosBundleId: 'com.example.moviles',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC7vGyEwvprHQ6C8hh8zatg--ymGEmdgJc',
    appId: '1:939281998082:ios:69ea384051884c4906621b',
    messagingSenderId: '939281998082',
    projectId: 'moviles-e0d1e',
    storageBucket: 'moviles-e0d1e.appspot.com',
    iosBundleId: 'com.example.moviles.RunnerTests',
  );
}
